### PR TITLE
Fix Release: run `sbt`, not `./sbt`

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
@julienrf I see that `ci` is not a required step to pass. Could you please make it so? :pray:

**Review by sjrd — APPROVED** [review]

**Comment by sideeffffect** [comment]
Nice! A SNAPSHOT version has been published
https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/sbt-missinglink_2.12_1.0/0.3.2+8-eb73a5c8-SNAPSHOT/

Now we can try to create a Release from GitHub UI and see whether it results in a successful publish to Maven Central :+1:

**Comment by julienrf** [comment]
@sideeffffect I thought you would have the rights to publish the release by yourself, and also to set the `ci` as a required step. Could you please double check?

**Comment by sideeffffect** [comment]
New version [`0.3.3`](https://repo1.maven.org/maven2/ch/epfl/scala/sbt-missinglink_2.12_1.0/0.3.3/) is out :tada: 

But I don't have privileges to configure protected branches
image

**Comment by julienrf** [comment]
Good job, thank you for your work! I granted you the required privileges (and I also changed the configuration for the main branch, I hope I did it correctly).

**Comment by sideeffffect** [comment]
Yep, seems good :+1: Thank you too :smiley:

**Pull request merged**
