### PR TITLE
upgrade missinglink to 0.1.4

### PR DESCRIPTION
**Pull request by mattnworb**
https://github.com/spotify/missinglink/releases/tag/v0.1.4
https://github.com/spotify/missinglink/releases/tag/v0.1.3

### CODE REVIEW

**Comment by sjrd** [comment]
It seems version v0.1.4 has not yet reached Maven Central.

**Comment by mattnworb** [comment]
I only cut the release about an hour or so ago, I should have waited to open this PR, sorry.

**Comment by sjrd** [comment]
It still cannot resolve v0.1.4 12 hours later. Are you sure everything went well with the release?

**Comment by mattnworb** [comment]
Seems like something must have gone wrong, I’ll reopen this once fixed.

**Pull request closed without merging**
